package presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import objetosNegocio.Jugador;

/**
 * Clase para el loggin.
 * @author Javier Obeso, J. Armando Méndez, J. Eduardo Montoya, L. Enrique Mendoza
 */
public class Loggin extends javax.swing.JFrame {
    private Jugador jugador;
    
    /**
     * Constructor principal.
     */
    public Loggin() {
        centraVentana();
        initComponents();
    }

    private void centraVentana() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width/2, height/2);		

        setLocationRelativeTo(null);
        setIconImage (new ImageIcon(getClass().getResource("/imagenes/icon.jpg")).getImage());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioLbl = new javax.swing.JLabel();
        nicknameTxt = new javax.swing.JTextField();
        nicknameLbl = new javax.swing.JLabel();
        aceptarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        avatarLbl = new javax.swing.JLabel();
        avatarCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Timbiriche");

        inicioLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inicioLbl.setText("Inicio de sesión");

        nicknameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nicknameLbl.setText("Nickname");

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares/Avatar1.jpg"))); // NOI18N

        avatarLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avatarLbl.setText("Avatar");

        avatarCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        avatarCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Avatar 1", "Avatar 2", "Avatar 3", "Avatar 4", "Avatar 5", "Avatar 6" }));
        avatarCB.setToolTipText("");
        avatarCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avatarCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(inicioLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicknameLbl)
                            .addComponent(nicknameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(aceptarBtn))
                                    .addComponent(avatarLbl)
                                    .addComponent(avatarCB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicioLbl)
                .addGap(18, 18, 18)
                .addComponent(nicknameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicknameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(avatarLbl)
                        .addGap(18, 18, 18)
                        .addComponent(avatarCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(avatar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salirBtn)
                    .addComponent(aceptarBtn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        if (nicknameTxt.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "No ha ingresado su Nickname.");
        } else {
            jugador = new Jugador (nicknameTxt.getText(), avatar.getIcon());
            Inicio ini = new Inicio (jugador);
            ini.setVisible(true);
            this.setVisible(false); 
        }
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void avatarCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avatarCBActionPerformed
        ImageIcon av = (ImageIcon) avatar.getIcon();
        
        switch (avatarCB.getSelectedItem().toString()){
            case "Avatar 1":
                av = new ImageIcon(getClass().getResource("/avatares/avatar1.jpg"));
                break;
            case "Avatar 2":
                av = new ImageIcon(getClass().getResource("/avatares/avatar2.jpg"));
                break;
            case "Avatar 3":
                av = new ImageIcon(getClass().getResource("/avatares/avatar3.jpg"));
                break;
            case "Avatar 4":
                av = new ImageIcon(getClass().getResource("/avatares/avatar4.jpg"));
                break;
            case "Avatar 5":
                av = new ImageIcon(getClass().getResource("/avatares/avatar5.jpg"));
                break;
            case "Avatar 6":
                av = new ImageIcon(getClass().getResource("/avatares/avatar6.jpg"));
                break;
        }
        
            avatar.setIcon(av);  
    }//GEN-LAST:event_avatarCBActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JLabel avatar;
    private javax.swing.JComboBox<String> avatarCB;
    private javax.swing.JLabel avatarLbl;
    private javax.swing.JLabel inicioLbl;
    private javax.swing.JLabel nicknameLbl;
    private javax.swing.JTextField nicknameTxt;
    private javax.swing.JButton salirBtn;
    // End of variables declaration//GEN-END:variables
}
